### ISSUE TITLE
Flushing logs slows down the application intensively (Error severity logs are flushed by default) we need a way to disable flushing

### ISSUE THREAD

**Issue by montss** [googleapis/java-logging#1143]
#### Environment details

1. Java version: 11
2.  version(s): com.google.cloud:libraries-bom:26.1.3 --> com.google.cloud:google-cloud-logging-bom:3.11.5 --> com.google.cloud:google-cloud-logging:3.11.5

#### Steps to reproduce

  Using JUL

#### Code example

```java
		LoggingHandler googleHandler = new LoggingHandler();
		googleHandler.setFlushLevel(LoggingLevel.EMERGENCY);
		Logger logger = Logger.getLogger(TestClass.class.getName());
		logger.addHandler(googleHandler);
```

#### Any additional information below
Related to:-
https://github.com/googleapis/google-cloud-java/issues/2796
https://github.com/googleapis/google-cloud-java/pull/4254

Setting the flush level to something higher than error doesn't work.
Also setting it though logging.properties file doesn't work 
`com.google.cloud.logging.LoggingHandler.flushLevel=EMERGENCY`

Error logs are flushed by default which causes massive slows down for that request overall
Profiling the system shows that most of the time are gone as a wall time on the flush call

We need a way to disable flushing for good.
Didn't try .setFlushLevel(Level.OFF);

**Comment by losalex** [comment]
Thanks @montss for opening this issue. Just to clarify - calling `setFlushLevel(Level.EMERGENCY)` in code was not working for you, correct?

**Comment by montss** [comment]
> Thanks @montss for opening this issue. Just to clarify - calling `setFlushLevel(Level.EMERGENCY)` in code was not working for you, correct?

Correct, calling `setFlushLevel(Level.EMERGENCY)` didn't work nor setting it through the `logging.properties` file 
`com.google.cloud.logging.LoggingHandler.flushLevel=EMERGENCY`

**Comment by daniel-sanche** [comment]
I don't have much context on this, but possibly related issue: https://github.com/googleapis/java-logging-logback/pull/319

**Comment by losalex** [comment]
> I don't have much context on this, but possibly related issue: [googleapis/java-logging-logback#319](https://github.com/googleapis/java-logging-logback/pull/319)

Thanks @daniel-sanche for context! The one issue you shared indeed related to java-logback and is not relevant for java-logging.

**Comment by losalex** [comment]
@montss , I checked in a fix - would you please be able to test it and let me know it works for you?

**Comment by losalex** [comment]
Resolving this issue for now - feel free to reopen if it doesnt work or you have any other issues

**Comment by montss** [comment]
Thank you very much!
We can now turn off flushing.
