### ISSUE TITLE
LogEntries being inconsistently swallowed with tomcat HTTP2 warnings

### ISSUE THREAD

**Issue by neostage** [googleapis/java-logging#1174]
#### Environment details

1. Cloud Run
2. OS type and version: openjdk:16-jdk-alpine
3. Java version: openjdk 16 / jvm target 11
4. version(s): 
this client library 3.11.1
spring boot 2.7.2
kotlin 1.7.10

#### Steps to reproduce

- deploy spring boot application using this library to cloud run
- generate some logs to cloud(not stdout)
- find in log explorer

#### Code example

```kotlin
// example
    private fun logCloudInternal(
        severity: Severity,
        entryBuilder: LogEntry.Builder
    ) {
        val context: Context? = ContextHandler().currentContext

        val httpRequest: HttpRequest? = context?.httpRequest
        val trace: String? = context?.traceId
        val span: String? = context?.spanId

        service.use { logging ->
            val entry = entryBuilder
                .setLogName(logName.value)
                .setSeverity(severity)
                .setResource(null)
                .setHttpRequest(httpRequest)
                .setTrace(trace)
                .setSpanId(span)
                .build()

            // Writes the log entry asynchronously
            logging.write(setOf(entry))
        }
    }
```

#### Stack trace
no stack trace / no exceptions
but in log explorer logs look like
```
2022-11-02 08:28:34 WARN 6 [x-cloud-trace-context=] --- [nio-8080-exec-3] o.a.c.h.Http2Parser : Connection [4], An unknown setting with identifier [8] and value [1] was ignored
```
can be found(~~/logs/run.googleapis.com%2Fstdout) and log entries are not seem to be sent 

#### External references such as API reference guides

- https://nightlies.apache.org/tomcat/tomcat-9.0.x/coverage/org.apache.coyote.http2/Http2Parser.java.html
- https://nightlies.apache.org/tomcat/tomcat-9.0.x/coverage/org.apache.coyote.http2/Setting.java.html

#### Any additional information below

- logs are being swallowed frequently but not constantly
  - tomcat warning and log appears at the same time
  - sometimes tomcat warning shown but the log is not swallowed
- tomcat warning message `identifier [8] and value [1]` is always the same except `Connection [#]`
- tried to create new LoggingOptions per every log
- also tried to share same LoggingOptions
  - almost every log is being swallowed in this case

**Comment by losalex** [comment]
Thank you @neostage for opening this issue and sorry for late response. Unfortunately, I do not have enough experience with tomcat HTTP2, but I have a feeling the issue you facing might not be related to tomcat since correct me if I wrong, same code sometimes does produces log records shown in Cloud Log Explorer and in most cases not, right?
Can you please try running your code with flushing logs after each write? E.g., add call to `flush()` after writing and see if situation is improved:

```java
            // Writes the log entry asynchronously
            logging.write(setOf(entry))
            // Flush any pending log entries
            logging.flush();
```

**Comment by meredithslota** [comment]
Closing as stale.
