### ISSUE TITLE
Expose the interface for converting structured logs to string

### ISSUE THREAD

**Issue by minherz** [googleapis/java-logging#1260]
The only way to use logging agent ingestion with the library for writing structured payload is by using `write()` API call.
It cannot be used with JUL or using java-logging-logback because these interfaces support only string payload.

Since the library already implements the conversion of the structured logs into string for being printed to stdout for further ingestion by the logging agents, exposing this functionality as a public interface can be used to ingest logs using JUL or logback.

**Comment by losalex** [comment]
I am closing this issue since it seems has no much demand - feel free to reactivate if anyone thinks otherwise
