### ISSUE TITLE
fix: Remove environment tests from PR checks

### ISSUE THREAD

**Issue by losalex** [googleapis/java-logging#1287]
Environment tests (e.g. App Engine or Kubernetes) should be removed from PR checks and used only in daily tests.
It appears consuming lot of resources and in many cases fails due to resource exhausted error.

**Comment by cindy-peng** [comment]
Currently environment tests have already removed from the presubmit process:
https://critique.corp.google.com/cl/533460163

Closing the issue as this has been resolved.
