### ISSUE TITLE
How to write v2.LogEntry Protobufs

### ISSUE THREAD

**Issue by KaoruDev** [googleapis/java-logging#1298]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
I'm trying to write logs in the shape of `com.google.logging.v2.LogEntry`. However, the `#write` expects `com.google.logging.LogEntry`.

**Describe the solution you'd like**
Reasonable options might be:
1. an easy way to convert `com.google.logging.v2.LogEntry` into `com.google.logging.LogEntry`. 
1. overloaded `#write` method that accepts `com.google.logging.v2.LogEntry`.

**Describe alternatives you've considered**
I'm writing my own converter 😭 

**Additional context**
Sorry, if this method already exists, could you please point me to the docs?

**Comment by KaoruDev** [comment]
Ah I see there's already a function for this: https://github.com/googleapis/java-logging/blob/4cb2e2c0914cd5a8634a28aab6ff5cef27016ced/google-cloud-logging/src/main/java/com/google/cloud/logging/LogEntry.java#L56-L59

If I open a PR to add an overloaded `write` method to convert `v2.LogEntry` to `logging.LogEntry` using this function, would that be acceptable?

**Comment by losalex** [comment]
Sure @KaoruDev , feel free to open a PR to expose this function. Just one note - I guess for more universal use, instead of adding extra `write` method, perhaps we could expose converter functions, e.g. `LogEntry.fromPbFunction` and `LogEntry.toPbFunction`.

**Comment by cindy-peng** [comment]
Hi @KaoruDev, just want to follow up, are you still interested in adding extra `write` method for `com.google.logging.v2.LogEntry` here? Or the current `FROM_PB_FUNCTION ` is sufficient?

**Comment by KaoruDev** [comment]
hey @cindy-peng -- we've since moved away from using this library. I likely won't be able to contribute for the foreseeable future 😞
