### ISSUE TITLE
com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute' of service 'logging.googleapis.com'

### ISSUE THREAD

**Issue by mothukuri** [googleapis/java-logging#1317]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-logging/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version:
4.  version(s):

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```java
// example
```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by mothukuri** [comment]
Are there any optimizations that can be explored for the above error. We tried batching as mentioned here
https://github.com/googleapis/java-logging#controlling-the-batching-settings

**Comment by meredithslota** [comment]
The error details indicate you're hitting a quota. You can learn more about quotas for Cloud Logging here: https://cloud.google.com/logging/quotas Specifically, for write requests, you'd be bumping up against the API limit, described here: https://cloud.google.com/logging/quotas#api-limits although you'd need to look in your project to see if which limit (or both) is causing the issue. You can request changes to your quota here: https://cloud.google.com/logging/quotas#api-limits. There might be ways to optimize your batching as well, but without knowing how you currently have it configured, it's difficult to provide specific guidance. Typically, the guidance is to increase the size of the batch to reduce the volume of writes. There's additional guidance here: https://cloud.google.com/java/docs/reference/gax/latest/com.google.api.gax.batching.BatchingSettings

I hope this helps!
