### ISSUE TITLE
owlbot.py post-processing is not idempotent

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-logging#1348]
The owlbot post-processor runs after each commit on a PR. It's behavior must be idempotent or you risk incorrect behavior (it will run again on its own commit that was pushed). 

In #1347, it's adding the env vars section 4 times (we allow owlbot post-processor to run at most 4 times to prevent an infinite loop).

**Comment by suztomo** [comment]
@daniel-sanche Would you take a look? This was added in https://github.com/googleapis/java-logging/commit/ab496ad6c34fbec0de0764f7e202db61003efdbc

**Comment by daniel-sanche** [comment]
Ok, I'll try to look into this this week.

If you need a resolution sooner, it should be ok to remove those env vars for now

**Comment by losalex** [comment]
Fixed in [1347](https://github.com/googleapis/java-logging/pull/1347).
