### ISSUE TITLE
Replace internal Structs class with google-cloud-core version

### ISSUE THREAD

**Issue by kolea2** [googleapis/java-logging#1492]
Just merged in https://github.com/googleapis/sdk-platform-java/pull/2278, once it is released we should swap out any usages of https://github.com/googleapis/java-logging/blob/main/google-cloud-logging/src/main/java/com/google/cloud/logging/Structs.java with this upstream version instead.

**Comment by cindy-peng** [comment]
Looks like currently the change for google-cloud-core is still pending for release: https://github.com/googleapis/sdk-platform-java/pull/2290

Will start the swap once the change has been released.
