### ISSUE TITLE
Chore: remove direct dependency on google-cloud-shared-config

### ISSUE THREAD

**Issue by zhumin8** [googleapis/java-logging#1561]
Regarding this https://github.com/googleapis/java-logging/pull/1550
remove this direct dependency so that this repo only needs [sdk-platform-java-config](https://github.com/googleapis/java-logging/pull/1552) dependency.

cc. @diegomarquezp @blakeli0

**Comment by diegomarquezp** [comment]
Hi @zhumin8, a couple of quick questions. Should this be part of the current release cycle? Why is `google-cloud-shared-config` unnecessary compared to `sdk-platform-java-config`?

**Comment by cindy-peng** [comment]
Hi @zhumin8, I am also wondering the reason for removing this direct dependency. Could you help us understand why it is unnecessary and it is safe to remove `google-cloud-shared-config`?

**Comment by zhumin8** [comment]
@cindy-peng sorry for the delay, this message fall through the cracks and I just noticed it.

So `sdk-platform-java-config` consolidates configs from `google-cloud-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version property`. 
That said, this issue is obsolete as I see https://github.com/googleapis/java-logging/pull/1679 recently made the change.
