### ISSUE TITLE
Google Cloud Logging/Stackdriver doesn't include request ID field

### ISSUE THREAD

**Issue by ihsanhaikalz** [googleapis/java-logging#204]
I found it very interesting that the log from Google Cloud Logging/Stackdriver monitoring activities in my Bucket does not have the request ID. In [Google Storage access log](https://cloud.google.com/storage/docs/access-logs) it has the request ID of any activities happening in the Bucket. It would be nice if the log from the Stackdriver has request ID field that can be correlated to the Google Storage access log.

**Comment by minherz** [comment]
Closed due to the lack of actionable information
