### ISSUE TITLE
Fail to list existing Sinks

### ISSUE THREAD

**Issue by NicolaSpreafico** [googleapis/java-logging#214]
Hello,
In my Java application I implemented the Cloud Logging client in order to read the existing sinks.

This is a simple method I'm using to reproduce the issue:
```
@Test
public void testApi() throws Exception {
    InputStream jsonStream = new FileInputStream(CREDENTIAL_PATH);
    GoogleCredentials credentials = GoogleCredentials.fromStream(jsonStream).createScoped(Collections.singleton("https://www.googleapis.com/auth/logging.read"));

    Logging client = LoggingOptions.newBuilder().setCredentials(credentials).setProjectId("XXXXXXXX").build().getService();

    Page<Sink> sinks = client.listSinks();
    sinks.iterateAll().forEach(sink -> {
        System.out.println(sink.getName());
    });
}
```

When this code runs I'm getting this error:
```
java.lang.IllegalArgumentException: logging.googleapis.com/projects/XXXXXXXX/locations/global/buckets/_Required is not a valid sink destination
at com.google.cloud.logging.SinkInfo$Destination.fromPb(SinkInfo.java:348)
at com.google.cloud.logging.SinkInfo.fromPb(SinkInfo.java:592)
at com.google.cloud.logging.Sink.fromPb(Sink.java:259)
at com.google.cloud.logging.Sink$1.apply(Sink.java:267)
at com.google.cloud.logging.Sink$1.apply(Sink.java:264)
at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:605)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
at java.base/java.lang.Iterable.forEach(Iterable.java:74)
```

At first I tried to update the library up to latest version, I can see from [documentation](https://cloud.google.com/logging/docs/reference/libraries#client-libraries-install-java) that is using 7.0.1 while on [Maven repository](https://mvnrepository.com/artifact/com.google.cloud/libraries-bom) the latest version is 9.0.1.
Same error...

Using [API Explorer](https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.sinks/list) I can correctly list the 2 existing items, so it is strictly a client issue and not the API itself.
```
{
  "sinks": [
    {
      "name": "_Required",
      "destination": "logging.googleapis.com/projects/XXXXXXXX/locations/global/buckets/_Required",
      "filter": "LOG_ID(\"cloudaudit.googleapis.com/activity\") OR LOG_ID(\"externalaudit.googleapis.com/activity\") OR LOG_ID(\"cloudaudit.googleapis.com/system_event\") OR LOG_ID(\"externalaudit.googleapis.com/system_event\") OR LOG_ID(\"cloudaudit.googleapis.com/access_transparency\") OR LOG_ID(\"externalaudit.googleapis.com/access_transparency\")"
    },
    {
      "name": "_Default",
      "destination": "logging.googleapis.com/projects/XXXXXXXX/locations/global/buckets/_Default",
      "filter": "NOT LOG_ID(\"cloudaudit.googleapis.com/activity\") AND NOT LOG_ID(\"externalaudit.googleapis.com/activity\") AND NOT LOG_ID(\"cloudaudit.googleapis.com/system_event\") AND NOT LOG_ID(\"externalaudit.googleapis.com/system_event\") AND NOT LOG_ID(\"cloudaudit.googleapis.com/access_transparency\") AND NOT LOG_ID(\"externalaudit.googleapis.com/access_transparency\")"
    }
  ]
}
```

Also, trying with another project I'm getting the same issue.

Has something recently change on Cloud Logging service?
If there is a change indeed, is the client obsolete on retrieveing data?

Thanks
Regards

**Comment by NicolaSpreafico** [comment]
From source code I found where the problem occurs:
https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/SinkInfo.java#L340

It seems the new destination like
```
logging.googleapis.com/projects/XXXXXXXX/locations/global/buckets/_Required
```
is not yet managed (it is not a bucket, a dataset or a topic).

Basing on a reply from Google support `_Required` is automatically created and holds Admin Activity audit logs, System Event audit logs, and Access Transparency logs([Refer to documentation](https://cloud.google.com/logging/docs/buckets)).

It is a beta feature so maybe the library does not handle yet? This is breaking the "listSinks" method

**Comment by athakor** [comment]
@NicolaSpreafico These issue has been resolved here https://github.com/googleapis/java-logging/pull/226.

closing these issue as it's already resolved, feel free to reopen it if you face.

**Comment by chingor13** [comment]
Still need to release it. 2.0.0 is pending in master so we may need to backport and release a 1.x version with the cherry picked fix

**Comment by Daniel-Sanche** [comment]
Closing this since v2.0.0 has been released
