### ISSUE TITLE
Please support audit_log.proto

### ISSUE THREAD

**Issue by bytesandwich** [googleapis/java-logging#221]
Does this already exist or otherwise, where is the right place to put https://github.com/googleapis/googleapis/tree/master/google/cloud/audit in google's java APIs? 

The python library was kind enough to include this: https://github.com/googleapis/python-logging/issues/9#event-3610223548 in https://github.com/googleapis/python-audit-log/commits/master/google/cloud/audit

Could you please support this in java? Thank you.

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Will do

**Is your feature request related to a problem? Please describe.**
Problem is that I need to use AuditLogs in java code but the compiled proto doesn't seem available anywhere?

**Describe the solution you'd like**
What you want to happen.

I would like to be able to get an AuditLog type from some java package that I can get from googleapis through the central maven repo.

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

The alternative is adding build code to download the necessary dependencies with the right versions for our codebase, and download the protobuf file. We also need to make sure the right versions of additional protobuf tooling are in place and add tests to our infrastructure to make sure the protobuf succeeds to compile and ultimately is binary compatible with our other code that uses it.

Alternatively we could check in the protobuf but we still have to compile it. We could also compile the protobuf and check that in. For a codebase that involves largely Avro this is a headache either way.

**Comment by busunkim96** [comment]
CC @chingor13 @simonz130

**Comment by bytesandwich** [comment]
You know, if you're considering that. I don't want to introduce it as a blocker for this ticket but I think it might be good to produce example/test data for these protobufs next to the generic definitions? Perhaps is this already available?

If you had a generic project with json files or encoded protobuf files (in the abstract that get pulled into every language) that get generated into test packages in each language then it would really help enterprise use cases and it would also be a sticky feature to GCP.

The reason I suggest this is that each Google codebase in GCP is probably creating test cases anyway so you might as well bundle them together for internal efficiency and if you were to expose it as a service to customers it would just be that much more valuable.

Say for example I want to use pub/sub `gcloud` emulator locally - I (and anyone else who uses it with AuditLogs) will create test cases with static pb encoded values or json values in files. I'll have to scrape these from time to time from GCP and I'll still probably get surprised when the actual PB or json GCP schema changes - and then I'll come back and make a failing test.

What do you guys think? Would you propose this to whatever internal process you have? @simonz130 @busunkim96 @chingor13

**Comment by anantdamle** [comment]
+1
Turning out to be a big issue consuming LogEntry protos in Dataflow.

**Comment by chingor13** [comment]
`audit_log.proto` is generated in https://github.com/googleapis/java-common-protos/tree/master/proto-google-common-protos/src/main/java/com/google/cloud/audit and is part of `com.google.api.grpc:proto-google-common-protos version` 1.18.0 and higher.

**Comment by anantdamle** [comment]
Still unable to deserialize a LogEntry message in Java

e.g. Unit Test fails with message **"com.google.protobuf.InvalidProtocolBufferException: Cannot resolve type: type.googleapis.com/google.cloud.audit.AuditLog"**
```java
@Test
public void deserialize_valid() throws InvalidProtocolBufferException {
  String createRecord = TestResourceLoader.load("create_tag_request.json");
  LogEntry.Builder auditLogBuilder = LogEntry.newBuilder();
  JsonFormat.parser().merge(createRecord, auditLogBuilder);
  assertThat(auditLogBuilder.build()).isNotEqualTo(LogEntry.getDefaultInstance());
}
```

Where `create_tag_request.json` is 
```json
{
  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {},
    "authenticationInfo": {
      "principalEmail": "runner@organization.com"
    },
    "requestMetadata": {
      "callerIp": "1.2.3.4",
      "callerSuppliedUserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,gzip(gfe),gzip(gfe)",
      "requestAttributes": {
        "time": "2020-09-09T15:25:57.094999275Z",
        "auth": {}
      },
      "destinationAttributes": {}
    },
    "serviceName": "datacatalog.googleapis.com",
    "methodName": "google.cloud.datacatalog.v1.DataCatalog.CreateTag",
    "authorizationInfo": [
      {
        "resource": "projects/my-project-id/locations/us/entryGroups/@bigquery/entries/cHJvamVjdHMvZ29vZ2xlLmNvbTphbmFudGQvZGF0YXNldHMvTXlEYXRhU2V0L3RhYmxlcy9Nb2NrUGlpUHJvY2V",
        "permission": "datacatalog.tagTemplates.use",
        "granted": true,
        "resourceAttributes": {}
      }
    ],
    "resourceName": "projects/my-project-id/locations/us/entryGroups/@bigquery/entries/cHJvamVjdHMvZ29vZ2xlLmNvbTphbmFudGQvZGF0YXNldHMvTXlEYXRhU2V0L3RhYmxlcy9Nb2NrUGlpUHJvY2V",
    "request": {
      "@type": "type.googleapis.com/google.cloud.datacatalog.v1.CreateTagRequest"
    },
    "response": {
      "@type": "type.googleapis.com/google.cloud.datacatalog.v1.Tag"
    }
  },
  "insertId": "sb27clc2el",
  "resource": {
    "type": "audited_resource",
    "labels": {
      "method": "google.cloud.datacatalog.v1.DataCatalog.CreateTag",
      "project_id": "my-project-id",
      "service": "datacatalog.googleapis.com"
    }
  },
  "timestamp": "2020-09-09T15:25:57.088307939Z",
  "severity": "NOTICE",
  "logName": "projects/my-project-id/logs/cloudaudit.googleapis.com%2Factivity",
  "receiveTimestamp": "2020-09-09T15:25:58.986691326Z"
}
```
