### ISSUE TITLE
com.google.logging.v2.LoggingClient.listLogEntries(logsNames, ""/*filter*/, ""/*orderBy*/).iterateAll() consistently takes 4-5 min to return some 160KB of log entries

### ISSUE THREAD

**Issue by sten1ee** [googleapis/java-logging#264]
That's the code snippet that I am testing with and the call to `listLogEntries(..)` consistently takes 4-5 minute to return some 160KB of json-encoded LogEntries, which is too much time I think.
```java
        try (var loggingClient = LoggingClient.create()) {
            ParentName parent = OrganizationName.of(".........."); // our org Id goes here
            for (String logName : loggingClient.listLogs(parent).iterateAll()) {
                logger.warn("Found log {}", logName);
            }      
            List<String> logsNames = Collections.singletonList(parent.toString());
            String filter = "";
            String orderBy = "timestamp";
            for (LogEntry logEntry : loggingClient.listLogEntries(logsNames, filter, orderBy).iterateAll()) {
                logger.warn("\n\t{}", logEntry);
            }
        }
```
#### Environment details

1. Cloud API: google-cloud-logging 
2. OS type and version: MacOS 10.14.6
3. Java version: openjdk version "11.0.2" 2019-01-15
4. google-cloud-java version(s):1.102.0

#### Steps to reproduce
The code above explains it.
More details: our organization in Google Cloud is registered and verified 3-4 days ago, and contrary to the suggestions by the setup 'wizard' I did have not setup a billing account, nor have I started the 2-weeks trial period and claimed the $300 of free-ware.

**Comment by sten1ee** [comment]
What I have found so far:
The data_access log shows that the `listLogs` request gets its response rather quickly and then 24 requests to `listLogEntries` are made (interval between each consecutive two of them being 16-19 sec):
```json
/* request to listLogs */
proto_payload {
  type_url: "type.googleapis.com/google.cloud.audit.AuditLog"
  value: "..."
}
insert_id: "g3d8l5dks2h"
resource {
  type: "global"
}
timestamp {
  seconds: 1601453182
  nanos: 327393187
}
severity: INFO
log_name: "organizations/669161410196/logs/cloudaudit.googleapis.com%2Fdata_access"
receive_timestamp {
  seconds: 1601453183
  nanos: 28773864
}

/* 1st request to listLogEntries */
proto_payload {
  type_url: "type.googleapis.com/google.cloud.audit.AuditLog"
  value: "..."
}
insert_id: "1y7nhy9dl43l"
resource {
  type: "logging_log"
  labels {
    key: "name"
    value: ""
  }
}
timestamp {
  seconds: 1601453182
  nanos: 774822921
}
severity: INFO
log_name: "organizations/669161410196/logs/cloudaudit.googleapis.com%2Fdata_access"
receive_timestamp {
  seconds: 1601453198
  nanos: 223120978
}

/* 2nd request to listLogEntries */
proto_payload {
  type_url: "type.googleapis.com/google.cloud.audit.AuditLog"
  value: "..."
}
insert_id: "198rvqtdq3hv"
resource {
  type: "logging_log"
  labels {
    key: "name"
    value: ""
  }
}
timestamp {
  seconds: 1601453198
  nanos: 34850807
}
severity: INFO
log_name: "organizations/669161410196/logs/cloudaudit.googleapis.com%2Fdata_access"
receive_timestamp {
  seconds: 1601453215
  nanos: 658142204
}

/*** ~22 more requests to listLogEntries, issued 16-19 sec apart ***/
```

**Comment by sten1ee** [comment]
My experiments show that the performance is rather inconsistent.
E.g. ~10 hours ago, October 4th, 2020, at around 7pm GMT, fetching the log(s) was blazingly fast - for multiple rounds it took only around 17-20 sec to finish.
And now, as I am writing this it is painfully slow again - 4-5 minutes
And the odd thing is it the 'checking there are no more entries' part that takes that much time - when fetching in 'desc' order, the actual fetching and printing is done in 18 sec, and then it takes 5 more minutes for the LogEntriy(s) iterator to declare the iteration finished.
When fetching in 'asc' order, my guess is that due to the natural order of storing the log entries, that 4-5 minutes overhead happens before any actual entries are returned from the API, as the whole sequence needs to be sorted in reverse order first.

**Comment by suraj-qlogic** [comment]
```listLogEntries``` is async function and used to retrieve log entries that originated from a gcp project.
 
This methods return paginated results under certain circumstances.The number of results per page is controlled by the pageSize property.By setting pageSize field which is normally used for The maximum number of results to return from this request. Non-positive values are ignored. The presence of nextPageToken in the response indicates that more results might be available. In both gRpc and rest api list log request you can able set pageSize field like below and please let us know it's help you.
 
 **For Rest Client Code:** 
```javascript
 try (LoggingClient loggingClient = LoggingClient.create()) {
      ProjectName parent = ProjectName.of("gcp-project-id"); // our project Id goes here
      List<String> logsNames = Collections.singletonList(parent.toString());
      String filter = "logName=\"projects/project-name/logs/my-test-log\"";
      String orderBy = "timestamp";
      ListLogEntriesRequest request =
          ListLogEntriesRequest.newBuilder()
              .addAllResourceNames(logsNames)
              .setFilter(filter)
              .setOrderBy(orderBy)
              .setPageSize(1000)
              .build();
      LoggingClient.ListLogEntriesPagedResponse listLogEntriesPagedResponse =
          loggingClient.listLogEntries(request);
      for (LogEntry logEntry : listLogEntriesPagedResponse.iterateAll()) {
        System.out.println(logEntry.getLogName());
      }
    } catch (IOException e) {
     
    }
 ```
**For gRpc Client Code:**
```javascript
    LoggingOptions options = LoggingOptions.getDefaultInstance();
    String logName = "my-test-log";
    try (Logging logging = options.getService()) {
      String logFilter = "logName=projects/" + options.getProjectId() + "/logs/" + logName;
      // List all log entries
      Page<LogEntry> entries = logging.listLogEntries(EntryListOption.filter(logFilter),EntryListOption.pageSize(1000));
      do {
        for (LogEntry logEntry : entries.iterateAll()) {
          System.out.println(logEntry.getLogName());
        }
        entries = entries.getNextPage();
      } while (entries != null);
    }catch (IOException e) {
     
    }
```
