### ISSUE TITLE
What is the actual Java class behind the @type="type.googleapis.com/ccc_hosted_reporting.ActivityProto" ?

### ISSUE THREAD

**Issue by sten1ee** [googleapis/java-logging#298]
(This is related to https://github.com/googleapis/java-logging/issues/269)

Looking at the logs obtained through the gcloud tool, it is evident that gcloud does use the v2 API.
And it is evident that gcloud knows which is the actual Java class that is 'hidden' behind the @type URL ***type.googleapis.com/ccc_hosted_reporting.ActivityProto*** because the metadata properties are properly listed by gcloud (see the list excerpt bellow);
Question is: How do I find which is that class in order to add the appropriate dependency it in my project's .pom file, import the friggin' class, and add its descriptor to the TypeRegistry so that I can also enjoy reading the aforementioned metadata that is accessible to the gcloud tool?
(I've been lucky enough to find how to do that with com.google.iam.v1.logging.AuditData, but ActivityProto seems to be a real "undercover" class ...)

(Please, refrain from answering "Use the v1 logging API instead" - it is not very helpful in that particular case.)
```
 {
    "insertId": ...
    "logName": ...,
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "authenticationInfo": {
        "principalEmail": ...
      },
      "metadata": {
        "@type": "type.googleapis.com/ccc_hosted_reporting.ActivityProto",
        "activityId": {
          "timeUsec": "1603364003491730",
          "uniqQualifier": "235331067176"
        },
        "event": [
          {
            "eventName": "login_success",
            "eventType": "login",
            "parameter": [
              {
                "label": "LABEL_OPTIONAL",
                "name": "login_type",
                "type": "TYPE_STRING",
                "value": "google_password"
              },
              {
                "label": "LABEL_REPEATED",
                "multiStrValue": [
                  "password"
                ],
                "name": "login_challenge_method",
                "type": "TYPE_STRING"
              },
              {
                "boolValue": false,
                "label": "LABEL_OPTIONAL",
                "name": "is_suspicious",
                "type": "TYPE_BOOL"
              },
              {
                "label": "LABEL_OPTIONAL",
                "name": "dusi",
                "type": "TYPE_STRING",
                "value": "INLWqOPzmfHMuQE"
              }
            ]
          }
        ]
      },
      "methodName": "google.login.LoginService.loginSuccess",
      "serviceName": "login.googleapis.com"
      ...
    },
    "receiveTimestamp": "2020-10-22T11:40:43.397414059Z",
    "timestamp": "2020-10-22T10:53:23.491730Z"
    ...
  }
```

**Comment by simonz130** [comment]
gcloud is implemented in python. Java, python, node and go clients for logging are handwritten. Java logging client doesn't support recognizing audit logs yet.
