### ISSUE TITLE
Make `LoggingEventEnhancer` more generic so can be used in more implementations 

### ISSUE THREAD

**Issue by dansiviter** [googleapis/java-logging#32]
**Is your feature request related to a problem? Please describe.**
Currently only `com.google.cloud.logging.logback.LoggingAppender` can enhance using information contained within the logging event. This isn't possible via the JDK logger although it should be.

 **Describe the solution you'd like**
Replace `com.google.cloud.logging.logback.LoggingEventEnhancer` with `com.google.cloud.logging.LoggingEventEnhancer` that has a class structure similar to:

```
@FunctionalInterface
public interface LoggingEventEnhancer<E> {
  void enhanceLogEntry(LogEntry.Builder builder, E event);
}
```

For backwards compatibility `com.google.cloud.logging.logback.LoggingEventEnhancer` could then change to:
```
public interface LoggingEventEnhancer extends com.google.cloud.logging.LoggingEventEnhancer<ILoggingEvent> {
   ...
}
```

 **Describe alternatives you've considered**
None

 **Additional context**
The JDK logger `com.google.cloud.logging.LoggingHandler` should then be enhanced to perform the enhancement using the new class. The old `com.google.cloud.logging.LoggingEnhancer` could be deprecated as its functionality could be subsumed by the new one.

**Comment by minherz** [comment]
@dansiviter do you still get these errors?

**Comment by minherz** [comment]
Thank you for your proposal. Indeed it enhances the abilities to customize the published logs by introducing a common logic across the application. We consider this change to be a breaking change. It cannot be implemented without either creating a flow that duplicates the existing method or by changing the existing `LoggingEnhancer` interface. It means this change can be introduced only within the next major release.
Please, see if the next release (probably 3.6) that introducing automatic metadata population helps you with some of the tasks for automatic log entry enhancement. See PR #808 for more details.

**Comment by losalex** [comment]
I am closing this issue since seems it is pretty old and apparently seems there is no much demand for this feature - please let me know if anyone thinks otherwise
