### ISSUE TITLE
Resource Labels Pod ID and Namespace ID are using the Name not the ID properties

### ISSUE THREAD

**Issue by twistedpair** [googleapis/java-logging#352]
The following values are incorrectly populated by [`MonitoredResourceUtil`](https://github.com/googleapis/java-logging/blob/b3c1b68712060299c9df5928ec011f556b8340ad/google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java#L165)
- `resoure.labels.pod_id`
- `resoure.labels.namespace_id`

The values being used are the **name** value of the respective entities, not the ID properties.

This is inconsistent with the Kubernetes API, and with other appenders used within GKE (e.g. the Fluentd appender), which properly populate the `pod_name` and `namespace_name` labels with the `metadata.name` property.

**Expected Behavior**

- `resoure.labels.pod_id` <- `pod.metadata.uid`
- `resoure.labels.namespace_id` <- `namespace.metadata.uid`
- `resoure.labels.pod_name` <- `pod.metadata.name`
- `resoure.labels.namespace_name` <- `namespace.metadata.name`

**Impact**
The present bug means that you must search in cloud logging with extra factually incorrect predicates like
```sql
resource.labels.pod_name="my-pod-name" OR resource.labels.pod_id="my-pod-name"
```
and means certain Stackdriver log based metrics and filters are not possible due to this inaccuracy. 

Since other GKE tools like the built in Fluentd appender properly set `resource.labels.pod_name`, example Fluentd output below:

![image](https://user-images.githubusercontent.com/1573793/101296140-d8445380-37ef-11eb-8387-a20ef3d1f6e3.png)

#### Environment details

1. Specify the API: Cloud Logging, e.g. used with the [Google Logback Cloud Appender](https://github.com/googleapis/java-logging-logback)
2. OS type and version: all
3. Java version: all
4. logging version(s): all

#### Steps to reproduce

  1. Emit Java log line
  2. View results in Cloud Logging

#### External references such as API reference guides

- [Kubernetes Object Metadata Spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#objectmeta-v1-meta)

#### Any additional information below

While changing the `pod_id` value to the correct `entity.metadata.uid` property would possibly impact library users, adding the `pod_name` and `namespace_name` labels, with the correct values, would allow Cloud Logging users to properly search by the name labels across all logging sources.

**Comment by suraj-qlogic** [comment]
@twistedpair,Thanks for filling issue.For a Kubernetes API container instance ```k8s_container``` is used as monitored resourceType.
I have been already submitted PR for this future which is under review.Please follow here [java-logging-206](https://github.com/googleapis/java-logging/issues/206)  for progress/work related to your request.

**Comment by twistedpair** [comment]
Thanks, @suraj-qlogic . Glad to see your PR merged.

Looks like `namespace_id` will still be the wrong value though, but that seems to be a bug in the underlying GCE metadata server. I'll update this issue.

**Comment by minherz** [comment]
@twistedpair should renaming `pod_id` to `pod_name` and `namespace_id` to `namespace_name` be sufficient to resolve the problem? from the report it looks like the current label naming is misleading and does not match the logging that is captured from STDOUT by Logging agent. however, i would like to confirm it before applying the change.

**Comment by minherz** [comment]
I see that the code [uses](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java#L95-L100) `pod_id` and `namespace_id` labels with the old resource type name: `container`. The `k8s_container` resource type is populated with the expected labels (`pod_name` and `namespace_name`). There is PR #641 that handles the change of the resource type name. After the merge, the expected set of label names will be populate.
