### ISSUE TITLE
Cloud Functions, Logback LoggingAppender, and User Labels

### ISSUE THREAD

**Issue by wko27** [googleapis/java-logging#406]
Hello!

We're using SLF4J combined with google-cloud-logging-logback from com.google.cloud.libraries-bom version 8.0.0, and specifically deploying our code using Google Cloud Functions.

We've been using the default ch.qos.logback.core.ConsoleAppender which allows us to query for logs on StackDriver using GCP's Logs Explorer tool.  We wanted to explore adding user labels to our logs to make them easier to filter upon.

Documentation seemed to indicate that the correct way to do this is to add a separate appender 'com.google.cloud.logging.logback.LoggingAppender' and include a Logback enhancer.  However, the LogEntry values created this way do not include the default resource.labels.function_name or execution id labels.

Is there a recommended way to include both the default labels (execution id, function name, etc) and user labels while still using standard SLF4J loggers?

Thank you for any assistance.

**Comment by simonz130** [comment]
Resource auto-detection in Cloud Functions is not yet supported in java-logging library. This PR #533 is first step in the process of detecting execution id, function name, etc. We expect to fully wrap this in Q3 2021. 
At the end of this effort we'll support:

1) Logging into stdout in structured way, including detecting resource (e.g. Cloud Function)
2) Logging directly into Cloud Logging BE, auto-detecting all LogEntry fields that are feasible to detect (e.g. severity, resource, traceId, etc.)

I'm closing this ticket as PR #533 is start of this work and we're actively working on adding this support now.
