### ISSUE TITLE
Cloud Logging: does not work for Java Cloud Functions

### ISSUE THREAD

**Issue by knyttl** [googleapis/java-logging#432]
#### Environment details

- OS type and version: Cloud Logging Java11 environment
- Java version: Java11

#### Steps to reproduce

Try to write any LogEntry with Java11 Cloud Function with appropriately set service account.

It will fail with: `io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 49.998533332s.` (stacktrace below). 

The very same code will work correctly with Cloud Run and the same service account.

#### Code example

```java
val entry = {any-logging-entry}
val logging = LoggingOptions
        .getDefaultInstance()
        .getService()
logging.write(Collections.singleton(entry))
```

#### Stack trace
```
https://gist.github.com/knyttl/280b465c7ab4135a41f12e77eb07efee
```

**Comment by knyttl** [comment]
I found the problem - Cloudfunction MUST NOT log asynchronously, because if they finish earlier, the log will not be published correctly.

```kotlin
logger.synchronicity = SYNC
```

This should be better documented.

**Comment by Daniel-Sanche** [comment]
Right now Cloud Functions isn't officially supported by this library, but we're working hard on adding better support over the next couple quarters.

**Comment by minherz** [comment]
The provided minimal example in the [prev. comment](https://github.com/googleapis/java-logging/issues/432#issuecomment-774528399) does not build. Use the following instead:

The code:
```java
package com.example;

import com.google.cloud.functions.HttpFunction;
import com.google.cloud.functions.HttpRequest;
import com.google.cloud.functions.HttpResponse;
import com.google.cloud.logging.Logging;
import com.google.cloud.logging.LoggingOptions;
import com.google.cloud.logging.LogEntry;
import com.google.cloud.logging.Payload.StringPayload;
import com.google.cloud.logging.Severity;
import java.util.Collections;

public class Example implements HttpFunction {
    @Override
    public void service(HttpRequest request, HttpResponse response) throws Exception {
        Logging logging = LoggingOptions.getDefaultInstance().getService();
        LogEntry logEntry = LogEntry
            .newBuilder(StringPayload.of("test log message"))
            .setLogName("cloud-func-test-logging-logger")
            .setSeverity(Severity.INFO)
            .build();
        logging.write(Collections.singleton(logEntry));
    }
}
```
and add the following into pom.xml file under `<dependencies>` element:
```
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-logging</artifactId>
    <version>3.1.1</version>
  </dependency>    
```

**Comment by minherz** [comment]
Like @knyttl described in the [comment](https://github.com/googleapis/java-logging/issues/432#issuecomment-781626376) logging library in JAVA sends logs asynchronously by default. It is done to allow batching multiple write calls into one and to minimize API call quota consumption. The sentence about it will be added to README of the repository.
The work will be tracked via issue #665
