### ISSUE TITLE
Timestamp Precision

### ISSUE THREAD

**Issue by dansiviter** [googleapis/java-logging#598]
**Is your feature request related to a problem? Please describe.**
Although the underlying `com.google.logging.v2.LogEntry` supports timestamps with nanosecond precision, `com.google.cloud.logging.LogEntry` only supports millisecond truncating the data.

**Describe the solution you'd like**
Replace the current `long` value representing milliseconds with `com.google.cloud.Timestamp`.

**Describe alternatives you've considered**
The only way is to use the protobuf classes directly or using ReST API which is cumbersome.

**Additional context**
N/A

**Comment by minherz** [comment]
Hello,
The logging library uses gRPC API to call Logging APIs. The value is returned as [`com.google.protobuf.Timestamp`](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Timestamp) and not `com.google.cloud.Timestamp`.
We would like to follow Java convention in representing time which is either using `long` number of milliseconds or using `java.sql.Timestamps`. We will check options to use timestamp with nanosecond resolutions for `Timestamp` and `ReceiveTimestamp` fields without having breaking changes in the library.

**Comment by dansiviter** [comment]
`java.time.Instant` would be more suitable, but it seems all the Google API libraries are linked to Java 1.7.

**Comment by minherz** [comment]
Thank you, @dansiviter

**Comment by minherz** [comment]
We will implement the change for all timestamp fields in the `LogEntry` class to support the legacy value in milliseconds (as `long`) and new value of the type `java.time.Instant` (thanx to the recent migration to Java 8). The legacy field will be marked for deprecation and will return the value of the `java.time.Instant.toEpochMilli()`.
