### ISSUE TITLE
broken Cloud Run envitonment test

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/java-logging#676]
The Cloud Run environment test is currently faling for Java ([example run](https://fusion.corp.google.com/invocation/58890479-7daa-4174-a439-21f0aae91449/buildlogs?target=cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-logging%2Fenvironment%2Fcloudrun%2Fpresubmit), or see testgrid). It seems to be encountering an issue similar to [this one](https://github.com/googleapis/java-logging/issues/432), logging `io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after x.xxxxs.`

**Comment by minherz** [comment]
Daniel, would it be possible to run tests for environments such as Cloud Run or Cloud Function with the synchronous configuration set to `SYNC` to confirm that the tests execute successfully this way?
If we can confirm that I will review all write log entry snippets to add the synchronicity setup code line and to comment it.

**Comment by daniel-sanche** [comment]
Hmm I just tried adding `logging.setWriteSynchronicity(Synchronicity.SYNC)` and it didn't seem to make a difference. 

FYI, for debugging purposes, you should be able to spin up a deployment to experiment with using `./envctl/envctl java cloudrun deploy` from the env-test-logging repo folder. Then you can trigger logs using `./envctl/envctl java cloudrun trigger simplelog logtext=hello`. Or you can make it deploy and then run the environment tests using `nox --session "tests(language='java', platform='cloudrun')"` 

Maybe I should present all this at the team meeting some time
