### ISSUE TITLE
Support Cloud Run Monitored Resource

### ISSUE THREAD

**Issue by meltsufin** [googleapis/java-logging#71]
**Is your feature request related to a problem? Please describe.**

Spring Cloud GCP Logging does not work with Cloud Run. The logs end up in the "Global" channel rather than the one for Cloud Run.

**Describe the solution you'd like**

The Cloud Run resource type `cloud_run_revision` should be automatically assigned to the log entries, similarly to how it's done for App Engine. See: [MonitoredResourceUtil](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java).

**Describe alternatives you've considered**

Using JSON-based logging on Cloud Run. It works better but has other issues like not supporting `TRACE` and `WARN` levels.

**Additional context**

Repro: https://github.com/meltsufin/cloud-run-helloworld

**Comment by saturnism** [comment]
Ideally, there is a single public API call to retrieve/produce a MonitoredResource.  This is a common library as oppose to only for logs.
