### ISSUE TITLE
feat: A stock LoggingEnhancer which uses SourceLocation.fromCurrentContext

### ISSUE THREAD

**Issue by bpcreech** [googleapis/java-logging#748]
**Is your feature request related to a problem? Please describe.**

The `LoggingEnhancer` interface is a neat way to add to a `LogEntry`. Meanwhile, `SourceLocation.fromCurrentContext` is a neat way to gather log call site information.

However, the two aren't connected yet! In fact, I don't see anything using `SourceLocation.fromCurrentContext`?

**Describe the solution you'd like**

Let's make a `LoggingEnhancer` which uses `SourceLocation.fromCurrentContext`!

*A note*: I suspect the interface of `SourceLocation.fromCurrentContext` is problematic for such a general use: it assumes the caller knows how many stack frames "up" the original call site was. I suspect that's going to be dependent on the logging configuration and frontend (e.g., flogger, slf4j, log4j, etc) and thus will be hard to work with. We have an internal implementation that works around this (basically: search the stack and find the first matching class and method name, which you can get from the log record, instead of assuming a fixed offset).

Note that getting the `sourceLocation` from the stack is "slow" (in my ad hoc microbenchmarking, it's about 1/4 of the overall cost of formatting and writing a typical log record to stderr) so I wouldn't necessarily install this by default, and I'd put it "behind" any downcast-based `LogSite` determining logic such as that alluded to in [this feature request](https://github.com/googleapis/java-logging/issues/747).

**Describe alternatives you've considered**

We currently have an internal implementation that does this, but it cannot make use of `com.google.cloud.logging` yet due to this and a couple other gaps. I'm filing this feature request in hopes of replacing our internal implementation.

**Additional context**

Contact with for any references to pre-existing internal implementations. :)

**Comment by minherz** [comment]
Duplicates #686
