### ISSUE TITLE
v3.4.0 release notes should mention the fix for issue #632

### ISSUE THREAD

**Issue by xhanin** [googleapis/java-logging#848]
After quite a long time investigating on performance and DEADLINE_EXCEEDED errors on a production server, I found this issue (which is not on that project, but we use the logback appender):
https://github.com/googleapis/java-logging-logback/issues/651

One comment is referencing the issue #632 on this project, and says it is part of version 3.4.0.

The release notes of that version do not mention the fix, despite the heavy impact of the bug / fix:
https://github.com/googleapis/java-logging/releases/tag/v3.4.0

If I understand the code correctly, it means that all versions between 2.1.4 and 3.4.0 (last november) were using single unary calls for each write log call, i.e. every single log when using the logback appender. The difference seems very important compared to batching calls, and has led us to situations exhausting the resources of a production server by stacking a high number of threads (we reached number like `grpc-default-executor-10011` in 10k+ logs of type DEADLINE_EXCEEDED).

So I'm surprised that such a big issue is mentionned only on a "cryptic" issue name ("No longer using GAX batching for WriteLogEntries" is cryptic for people only using a logback appender and assuming it works).

I think that would deserve better documentation, at least on the v3.4.0 release notes, but I would add something on the main README of both this project and googleapis/java-logging-logback (in the `Optimize log ingestion` section) to inform users and ask to upgrade their version. 

What do you think? Did I misunderstood the problem? Maybe the batching is not so important, and in our case the DEADLINE_EXCEEDED errors are related to something else and will probably still happen after an upgrade with the fix for #632?

**Comment by minherz** [comment]
Hi,
The release notes are auto-generated. We will see if it is possible to add this information into the release notes.

**Comment by minherz** [comment]
The [release notes](https://github.com/googleapis/java-logging/releases/tag/v3.4.0) in the Github were update.
