### ISSUE TITLE
Capture test sampled flag from x-cloud-trace-context

### ISSUE THREAD

**Issue by minherz** [googleapis/java-logging#854]
When auto-populating tracing information from the `x-cloud-trace-context` header, the trace sampled flag should be captured and the [`traceSampled`](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#FIELDS.trace_sampled) field populated.

Doing this will ensure the [integration](https://cloud.google.com/trace/docs/trace-log-integration) of the Cloud Logging with Cloud Tracing.

DO NOT capture trace sampled flag for W3C context (`traceparent`) because the meaning of the "trace sampling" flag and the requirements for the trace field in these two headers are different.

**Comment by losalex** [comment]
Closing this issue since there are plans to retire `x-cloud-trace-context` and add support for OpenTelemetry trace context propagation
