### ISSUE TITLE
Allow configuration for maxOutstandingElementCount and limitExceededBehavior

### ISSUE THREAD

**Issue by edudar** [googleapis/java-logging#953]
The current behavior is hardcoded as `Block` in `GrpcLoggingRpc`. This creates a problem, though. We run in a containerized environment with little overhead room for extra memory allocations. One of our services went down because Stackdriver was unavailable due to the 'quota exceeded' error, and log messages were piling up waiting to be sent. I'd sacrifice a few or a hundred log messages instead of a service. We use LoggingAppender with Logback. There seems to be no way to configure anything in the `FlowControlSettings`. I want to set a lower number for outstanding elements (like 1,000 instead of 100,000) and `Ignore`/`ThrowException` for limit behavior so that messages are discarded if they can't be delivered.

**Comment by blakeli0** [comment]
@edudar `FlowControlSettings` does expose `setMaxOutstandingElementCount`, see [here](https://github.com/googleapis/gax-java/blob/816e6665e06bc65cbaf2703617342c8db9780115/gax/src/main/java/com/google/api/gax/batching/FlowControlSettings.java#L78), is that good enough for you?

**Comment by edudar** [comment]
@blakeli0 none of these are accessible with v1 logging, from what I can tell. And that's what `com.google.cloud.logging.logback` uses. I see that there seems to be a way to do that in v2 via `LoggingClient(LoggingSettings->writeLogEntriesSettings->batchingSettings->flowControlSettings)`, probably, but that requires using logging client directly, which is not a feasible alternative.

**Comment by losalex** [comment]
@edudar , this is correct - I exposed an ability to set `BatchingSettings` through `LoggingOptions`, you can see linked code change. Please let me know if that resolves your issue or anything is missing.

**Comment by losalex** [comment]
Sure @edudar - I opened an issue for [903](https://github.com/googleapis/java-logging-logback/issues/903) in java-`logging-logback` to expose batching settings and I am closing this issue. Let me know if anything else is missing - thanks!
